name: Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pages-deploy
  cancel-in-progress: true

jobs:
  documentation:
    runs-on: macos-26
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable dev tooling
        run: touch .dev-tooling

      - name: Build Documentation
        run: |
          swift package --allow-writing-to-directory ./docs \
            generate-documentation \
            --target SwiduxRevenueCatPaywall \
            --target SwiduxRevenueCatPaywallUI \
            --enable-experimental-combined-documentation \
            --disable-indexing \
            --transform-for-static-hosting \
            --hosting-base-path /SwiduxRevenueCatPaywall \
            --output-path ./docs

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
